export const homeObjOne = {
  id: "catalog",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Catalog",
  headLine: "Catalog Head line",
  description: "s  asd  ds sa fd ffBla blas jljl kljlj kj ll ",
  buttonLabel: "Get catalog",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "Catalog",
  dark: true,
  start: true,
  primary: true,
  link: "/catalog",
  darkText: false
};
export const homeObj2 = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Top Line2",
  headLine: "Head line",
  description: "Bla blas jljl kljlj kj ll ",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/svg-1.svg"),
  alt: "Car",
  link: "/about",
  start: false,
  dark: false,
  primary: true,
  darkText: false
};
